apiVersion: v1
kind: Secret
metadata:
  name: user-db-secret
type: Opaque
data:
  # echo -n 'user' | base64 → dXNlcg==
  # echo -n 'password' | base64 → cGFzc3dvcmQ=
  DATABASE_USER: dXNlcg==
  DATABASE_PASSWORD: cGFzc3dvcmQ=