apiVersion: v1
kind: Service
metadata:
  name: otus-app-service
spec:
  selector:
    app: otus-app
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  type: ClusterIP  # ClusterIP | NodePort